# Generated by Django 5.1.3 on 2024-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(
                choices=[(False, "Not done"), (True, "Done")], default=False
            ),
        ),
    ]
